config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'

  root 'welcome#index'

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'adventurer/:id/fire' => 'adventurers#fire', as: 'fire_adventurer'
  get 'adventurer/:id/hire' => 'adventurers#hire', as: 'hire_adventurer'
  get 'adventurers/market' => 'adventurers#market', as: 'adventurer_market'
  get 'contract/:id/tasks/new' => 'tasks#new', as: 'new_contract_task'
  post 'adventurers/:id/contract/:id/tasks/create' => 'tasks#create', as: 'new_adventurer_contract_task'

  resources :sessions
  resources :profiles
  resources :guildhalls
  resources :bids, only: [:new, :create]
  resources :quests, only: [:index, :show] do
    resources :bids, only: [:new, :create]
  end
  resources :adventurers, only: [:new, :create, :show, :index]
  resources :users, only: [:new, :create, :destroy] do
    resource :profile, only: [:show, :edit]
    resource :guildhall, only: [:show, :edit]
  end
end

app/models/guildhall.rb
class Guildhall < ActiveRecord::Base
  belongs_to :user
  has_many :adventurers
  has_many :contracts

  after_initialize :init_guildhall

  private

  def init_guildhall
    self.gold ||= 10
    self.capacity ||= 4
  end
end

app/controllers/guildhalls_controller.rb
class GuildhallsController < ApplicationController
  before_filter :require_user, only:  [:edit, :update]
  before_filter :current_user_owns_guildhall, only: [:edit, :update]

  expose(:guildhalls)
  expose(:guildhall) do
    Guildhall.where("user_id = ?", params[:user_id]).first ||
    Guildhall.find(params[:id])
  end

  def update
    @guildhall = Guildhall.find(params[:id])

    if @guildhall.update_attributes(guildhall_params)
      redirect_to user_guildhall_path(@guildhall.user.id), notice: "Guild successfully updated."
    else
      render 'edit'
    end
  end

  private

  def current_user_owns_guildhall
    unless current_user.id == guildhall.user.id
      redirect_to :root
    end
    return false
  end

  def guildhall_params
    params.require(:guildhall).permit(:name)
  end
end

app/helpers/guildhalls_helper.rb
module GuildhallsHelper
end

app/views/guildhalls/edit.html.haml
%h1 Edit Guildhall

=form_for guildhall do |f|
  .field
    =f.label :name
    %br
    =f.text_field :name

  .field
    =f.submit "Update Guild"

app/views/guildhalls/show.html.haml
%h1= guildhall.name

=link_to "Edit Guildhall", edit_user_guildhall_path(guildhall.user.id)

%h3 Guildhall Status
%ul
  %li
    Gold:
    =guildhall.gold
  %li
    Capacity:
    =guildhall.capacity
  %li
    Total Salaries:
    =guildhall.adventurers.map {|a| a.salary}.inject { |sum, a| sum + a }

-if !guildhall.adventurers.empty?
  %h3 Adventurers
  %ul
    -guildhall.adventurers.each do |adventurer|
      %li=link_to adventurer.name, adventurer

-if !guildhall.contracts.empty?
  %h3 Current Quests:
  %ul
    -guildhall.contracts.each do |contract|
      %li
        .quest-title
          =contract.quest.title
        .quest-status
          -if contract.task == nil
            =link_to "Send adventurer on quest", new_contract_task_path(contract.id)
          -else
            = "#{contract.task.adventurer.name} is currently on this quest."