config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'

  root 'welcome#index'

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'adventurer/:id/fire' => 'adventurers#fire', as: 'fire_adventurer'
  get 'adventurer/:id/hire' => 'adventurers#hire', as: 'hire_adventurer'
  get 'adventurers/market' => 'adventurers#market', as: 'adventurer_market'
  get 'contract/:id/tasks/new' => 'tasks#new', as: 'new_contract_task'
  post 'adventurers/:id/contract/:id/tasks/create' => 'tasks#create', as: 'new_adventurer_contract_task'

  resources :sessions
  resources :profiles
  resources :guildhalls
  resources :bids, only: [:new, :create]
  resources :quests, only: [:index, :show] do
    resources :bids, only: [:new, :create]
  end
  resources :adventurers, only: [:new, :create, :show, :index]
  resources :users, only: [:new, :create, :destroy] do
    resource :profile, only: [:show, :edit]
    resource :guildhall, only: [:show, :edit]
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :user_owns_profile, only: [:edit, :update]

  expose(:profiles)
  expose(:profile) do
    Profile.where("user_id = ?", params[:user_id]).first ||
    Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update_attributes(profile_params)
      redirect_to user_profile_path(@profile.user.id), notice: "Profile successfully updated."
    else
      render 'edit'
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:display_name, :about)
  end

  def user_owns_profile
    unless profile.user.id == current_user.id
      redirect_to user_profile_path(profile.user.id), notice: "You can only edit your own profile!"
      return false
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
=form_for profile do |f|
  .field
    =f.label :display_name
    %br
    =f.text_field :display_name

  .field
    =f.label :about
    %br
    =f.text_field :about

  .field
    =f.submit("Update Profile")

app/views/profiles/show.html.haml
%h1
  -if profile.display_name.is_a?(NilClass)
    =profile.user.email
  -else
    =profile.display_name
-if current_user and current_user.profile.id == profile.id
  %ul
    %li=link_to "Edit My Profile", edit_user_profile_path(current_user.id)
    %li=link_to "Delete My Account", user_path(current_user.id), method: :delete, confirmation: "This cannot be undone. Are you sure you want to delete your account?"


%h2 About

%p= profile.about