config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'

  root 'welcome#index'

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'adventurer/:id/fire' => 'adventurers#fire', as: 'fire_adventurer'
  get 'adventurer/:id/hire' => 'adventurers#hire', as: 'hire_adventurer'
  get 'adventurers/market' => 'adventurers#market', as: 'adventurer_market'
  get 'contract/:id/tasks/new' => 'tasks#new', as: 'new_contract_task'
  post 'adventurers/:id/contract/:id/tasks/create' => 'tasks#create', as: 'new_adventurer_contract_task'

  resources :sessions
  resources :profiles
  resources :guildhalls
  resources :bids, only: [:new, :create]
  resources :quests, only: [:index, :show] do
    resources :bids, only: [:new, :create]
  end
  resources :adventurers, only: [:new, :create, :show, :index]
  resources :users, only: [:new, :create, :destroy] do
    resource :profile, only: [:show, :edit]
    resource :guildhall, only: [:show, :edit]
  end
end

app/models/adventurer.rb
class Adventurer < ActiveRecord::Base
  belongs_to :guildhall
  has_many :quest_logs
  has_one :task
  serialize :skills

  after_initialize :init_adventurer

  def level
    self.skills.values.inject {|sum, x| sum + x }
  end

  def salary
    (level / 4).floor + 1
  end

  def advance
    salary * 4
  end

  def go_on_quest(quest)
    quest_log = { success: true, body: "", steps_completed: 0 }
    skills_used = []
    quest.steps.each do |step|
      quest_log[:steps_completed] += 1
      quest_log[:body] += step[:description] + "\n"
      skills_used << determine_best_skill(step)
      if(attempt_step(step, skills_used.last))
        quest_log[:body] += step[:skills][skills_used.last] + "\n"
      else
        quest_log[:body] += step[:action_failure] + "\n"
        quest_log[:success] = false
        break
      end
    end

    skill = skills_used.sample
    self.skills[skill] = self.skills[skill].nil? ? 1 : self.skills[skill] + 1
    return quest_log
  end

  private
  def self.skill_list
    [:melee, :black_magic, :white_magic, :swimming, :climbing, :archery, :stealth, :lock_picking, :knowledge, :common_sense]
  end

  def init_adventurer
    self.name ||= Faker::Name.first_name + " " + Faker::Name.last_name
    self.guildhall_id ||= 0
    unless self.skills
      self.skills = { }
      3.times do
        skill = Adventurer.skill_list.sample
        self.skills.has_key?(skill) ? self.skills[skill] += 1 : self.skills[skill] = 1
      end
    end
  end

  def map_range (s, min1, max1, min2, max2)
    (min2 + (s - min1) * (max2 - min2) / (max1 - min1)).round(2)
  end

  def calc_prob(skill, difficulty)
    spread = skill.to_f - difficulty.to_f

    0.5 + map_range(spread, -50.0, 49.0, -2, 2)
  end

  def attempt_step(step, skill)

    if rand(1..100) < calc_prob(self.skills[skill], step[:difficulty]) * 100
      true
    else
      false
    end

  end

  def determine_best_skill(step)
    relevant_skills = {}

    step[:skills].each_key do |skill|
      if(self.skills.has_key?(skill))
        relevant_skills[skill] = self.skills[skill]
      end
    end

    best_skill = ""
    highest_level = 0

    relevant_skills.each do |skill, level|
      if level > highest_level then best_skill = skill end
    end

    if(best_skill == "") then best_skill = step[:skills].keys.first end

    best_skill
  end

end

app/controllers/adventurers_controller.rb
class AdventurersController < ApplicationController
  before_filter :require_user
  before_filter :user_owns_adventurer, only: [:fire]

  expose(:adventurers)
  expose(:adventurer)
  expose(:new_adventurers) { [Adventurer.create, Adventurer.create, Adventurer.create] }
  expose(:unemployed_adventurers) { Adventurer.where("guildhall_id = ?", 0) }
  expose(:guildhall) { current_user.guildhall }
  expose(:quest)

  def new
    session[:adventurer_ids] = new_adventurers.map { |a| a.id }
  end

  def fire
    adventurer.update_attributes(guildhall_id: 0, entered_market_at: Date.today)
    adventurer.save
    redirect_to user_guildhall_path(current_user.id), notice: "#{adventurer.name} has left your guild."
  end

  def quest
    quest_log = adventurer.go_on_quest(quest)
    adventurer.quest_logs.create(body: quest_log[:body], success: quest_log[:success])
  end

  def hire
    validation = validate_for_hire

    unless validation[:valid?]
      redirect_to :root, notice: validation[:reason] and return
    else
      guildhall.update_attribute(:gold, guildhall.gold - adventurer.advance)
      adventurer.update_attribute(:guildhall_id, guildhall.id)
      redirect_to adventurer_market_path, notice: "#{adventurer.name} is now a member of your guild."
    end

  end

  def create
    validation = validate_for_hire

    unless adventurer.temp == true and session[:adventurer_ids].include?(adventurer.id) and validation[:valid?]
      dump_temp_adventurers
      redirect_to :root, notice: validation[:reason] and return
    end

    adventurer.update_attributes(guildhall_id: current_user.guildhall.id, temp: false)

    dump_temp_adventurers

    if adventurer.save
      redirect_to user_guildhall_path(current_user.id), notice: "#{adventurer.name} hired!"
    else
      render :new, notice: "Something went wrong!"
    end

  end

  private
  def validate_for_hire
    validation = {}
    if adventurer.guildhall_id != 0
      validation[:reason] = "That adventurer is already employed."
    elsif guildhall.adventurers.count >= guildhall.capacity
      validation[:reason] = "You cannot hire any more adventurers. Your guild is at capacity."
    elsif guildhall.gold < adventurer.advance
      validation[:reason] = "You can't afford to hire this adventurer."
    end

    validation[:valid?] = validation[:reason].nil? ? true : false
    validation
  end

  def dump_temp_adventurers
    session[:adventurer_ids].delete_if {|id| id == adventurer.id}
    session[:adventurer_ids].each do |id|
      Adventurer.find(id).destroy
    end
    session[:adventurer_ids] = []
  end

  def deny_user_access
    redirect_to :root, notice: "You must be logged in to do that."
  end

  def user_owns_adventurer
    unless current_user.guildhall.id == adventurer.guildhall_id
      redirect_to :root
    end
    return false
  end

end

app/helpers/adventurers_helper.rb
module AdventurersHelper
end

app/views/adventurers/index.html.haml
%h1 Adventurers#index
%p Find me in app/views/adventurers/index.html.haml

app/views/adventurers/market.html.haml
%h1 Adventurer Market
%p The following adventurers are unemployed and looking for a guild to call their home.

%table
  %tr
    %th Name
    %th Skills
    %th Advance
  -unemployed_adventurers.each do |adventurer|
    %tr
      %td= adventurer.name
      %td
        %ul
          -adventurer.skills.each do |skill, level|
            %li= skill.to_s.gsub("_", " ") + " " + level.to_s
      %td= adventurer.salary * 4
      %td{id: "adventurer_#{adventurer.id}_form"}
        =link_to "Hire", hire_adventurer_path(adventurer.id)

app/views/adventurers/new.html.haml
%h1 Town Square

%p Several fresh recruits have gathered hoping for a chance to prove themselves

%table
  %tr
    %th Name
    %th Skills
  -new_adventurers.each do |adventurer|
    %tr
      %td= adventurer.name
      %td
        %ul
          -adventurer.skills.each do |skill, level|
            %li= skill.to_s.gsub('_', ' ').capitalize + " " + level.to_s
      %td{id: "adventurer_#{adventurer.id}_form"}
        =form_tag '/adventurers', method: :post do |f|
          =hidden_field_tag :adventurer_id, adventurer.id
          =submit_tag "Hire"

app/views/adventurers/show.html.haml
%h1= adventurer.name
-if current_user and current_user.guildhall.id == adventurer.guildhall_id
  =link_to "Fire Adventurer", fire_adventurer_path(adventurer.id)
%h2 Skills
%ul
  - adventurer.skills.each do |skill, level|
    %li= skill.to_s.gsub('_',' ').capitalize + ' ' + level.to_s