config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'

  root 'welcome#index'

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'adventurer/:id/fire' => 'adventurers#fire', as: 'fire_adventurer'
  get 'adventurer/:id/hire' => 'adventurers#hire', as: 'hire_adventurer'
  get 'adventurers/market' => 'adventurers#market', as: 'adventurer_market'
  get 'contract/:id/tasks/new' => 'tasks#new', as: 'new_contract_task'
  post 'adventurers/:id/contract/:id/tasks/create' => 'tasks#create', as: 'new_adventurer_contract_task'

  resources :sessions
  resources :profiles
  resources :guildhalls
  resources :bids, only: [:new, :create]
  resources :quests, only: [:index, :show] do
    resources :bids, only: [:new, :create]
  end
  resources :adventurers, only: [:new, :create, :show, :index]
  resources :users, only: [:new, :create, :destroy] do
    resource :profile, only: [:show, :edit]
    resource :guildhall, only: [:show, :edit]
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Guildmaster
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %header#header-area
      %div.container
        /Main Header Starts
        %div.main-header
          -[:notice, :error, :alert].each do |level|
            - unless flash[level].blank?
              %div
                %a{ href: "#", class: "close", data: { dismiss: "alert" } } &times;
                = flash[level]
    %ul
      - if !current_user
        %li=link_to "Sign up!", new_user_path
        %li=link_to "Log In", log_in_path
      - else
        %li=link_to "Log Out", log_out_path
        %li=link_to "My Profile", user_profile_path(current_user.id)
        %li=link_to "My Guildhall", user_guildhall_path(current_user.id)
        %li=link_to "Town Square", new_adventurer_path
        %li=link_to "Free Market", adventurer_market_path
        %li=link_to "Quest Bulletins", quests_path
    = yield